### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by emmanuelkamala**

### CODE REVIEW

**Comment by AdnanAfsari** [comment]
Adnan Afsari working on it

**Review by AdnanAfsari — CHANGES_REQUESTED** [review]
Hello @emmanuelkamala ✋ 

Nice work but you have to do little more work.

- I tried to run test in my local machine but 3 methods failed to pass the test, please check and make sure its working.

- Try to write at least two test case for every methods.

Please submit for another review after making these changes :)

Happy Coding

**Comment by bellom** [comment]
## Currently reviewing this PR

**Review by bellom — APPROVED** [review]
Hi @emmanuelkamala,
Great work making all the necessary corrections from the previous review....
All methods working fine, test failed when i break your code, good job :+1: 
## Congratulation :+1:

**Comment by emmanuelkamala** [comment]
Thank you!

**Pull request merged**
